name: 'Merge'

on:
  workflow_run:
    workflows:
      - 'Test'
    branches:
      - 'main'
    types:
      - 'completed'

jobs:
  merge:
    name: 'Merge'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.3.4
        with:
          ref: dev
          fetch-depth: 0
      - name: "Merge"
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git merge origin/main
          git push
